# Pandas Basics

**Importing the packages **

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Creating a dataframe **

In [2]:
print(np.random.rand(10,4))

[[0.66297255 0.71948627 0.4367043  0.21628206]
 [0.50449614 0.52872887 0.07554441 0.87472023]
 [0.63687629 0.58754778 0.07794952 0.66068495]
 [0.98452497 0.7116925  0.45932897 0.19342964]
 [0.07984338 0.79165499 0.5697473  0.79939392]
 [0.04524926 0.82168396 0.2989317  0.69270503]
 [0.954651   0.63255286 0.88304378 0.2730407 ]
 [0.75204776 0.02574816 0.72709243 0.00295502]
 [0.32177814 0.49835836 0.43033048 0.05792264]
 [0.72666345 0.58547874 0.8759525  0.17231654]]


In [2]:
df=pd.DataFrame(np.random.rand(10,4), columns=['A','B','C','D'])
print(df)

          A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
1  0.884613  0.366173  0.403009  0.059076
2  0.190153  0.379428  0.606521  0.670061
3  0.813650  0.865682  0.005590  0.833786
4  0.797834  0.530511  0.894112  0.368181
5  0.180576  0.837625  0.085812  0.325849
6  0.099598  0.170077  0.896005  0.045636
7  0.143263  0.313568  0.902985  0.922671
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656


In [3]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

**Creating a dataframe with dictionary **

In [4]:
dict1 = {'A' : [10,20],'B' : [20,100],'C' : [30,40],'D' : [40,50]}
df2 = pd.DataFrame(dict1)
print(df2)

    A    B   C   D
0  10   20  30  40
1  20  100  40  50


**Looking at the variable types **

In [5]:
df2.dtypes

A    int64
B    int64
C    int64
D    int64
dtype: object

**looking at the top few values, default 5 **

In [11]:
df.head()

A         B         C         D
0  0.794220  0.268694  0.556035  0.486056
1  0.991745  0.032538  0.959418  0.571117
2  0.173675  0.251969  0.698630  0.314125
3  0.515330  0.743632  0.975673  0.908048
4  0.789374  0.921929  0.135428  0.624495

**Looking at the last few values **

In [12]:
df.tail()

A         B         C         D
5  0.273274  0.739538  0.580346  0.091695
6  0.770175  0.097964  0.608022  0.929186
7  0.243849  0.083821  0.258348  0.379204
8  0.478665  0.901917  0.649005  0.218910
9  0.793143  0.298037  0.897777  0.835582

**To get the indexes **


In [13]:
#print(df)
df.index

RangeIndex(start=0, stop=10, step=1)

**To get the column names **

In [11]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [7]:
hasattr(df, 'A')

True

**To get the values **

In [16]:
df.values

array([[0.44270573, 0.4900834 , 0.6035361 , 0.43847876],
       [0.91464434, 0.70835844, 0.5611243 , 0.09116765],
       [0.62600018, 0.08533913, 0.68724173, 0.60111961],
       [0.35172865, 0.10541037, 0.92368395, 0.9330255 ],
       [0.93856373, 0.11712047, 0.51051402, 0.44075515],
       [0.44392989, 0.57688616, 0.65854799, 0.63839185],
       [0.82701844, 0.27447895, 0.80715525, 0.87586444],
       [0.4631822 , 0.99257977, 0.71516306, 0.08324801],
       [0.08139382, 0.29432629, 0.13518423, 0.99712372],
       [0.93046533, 0.62038728, 0.98596062, 0.4397428 ]])

**To get quick statistics about the data **

In [17]:
df.describe()

A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.601963   0.426497   0.658811   0.553892
std     0.293147   0.301833   0.238502   0.321110
min     0.081394   0.085339   0.135184   0.083248
25%     0.443012   0.156460   0.571727   0.438795
50%     0.544591   0.392205   0.672895   0.520937
75%     0.892738   0.609512   0.784157   0.816496
max     0.938564   0.992580   0.985961   0.997124

**For sorting the index **

In [21]:
df.sort_index(axis=0, ascending=False)

A         B         C         D
9  0.930465  0.620387  0.985961  0.439743
8  0.081394  0.294326  0.135184  0.997124
7  0.463182  0.992580  0.715163  0.083248
6  0.827018  0.274479  0.807155  0.875864
5  0.443930  0.576886  0.658548  0.638392
4  0.938564  0.117120  0.510514  0.440755
3  0.351729  0.105410  0.923684  0.933026
2  0.626000  0.085339  0.687242  0.601120
1  0.914644  0.708358  0.561124  0.091168
0  0.442706  0.490083  0.603536  0.438479

**For sorting by a column **

In [23]:
df.sort_values(by='A', ascending = True)

A         B         C         D
8  0.081394  0.294326  0.135184  0.997124
3  0.351729  0.105410  0.923684  0.933026
0  0.442706  0.490083  0.603536  0.438479
5  0.443930  0.576886  0.658548  0.638392
7  0.463182  0.992580  0.715163  0.083248
2  0.626000  0.085339  0.687242  0.601120
6  0.827018  0.274479  0.807155  0.875864
1  0.914644  0.708358  0.561124  0.091168
9  0.930465  0.620387  0.985961  0.439743
4  0.938564  0.117120  0.510514  0.440755

## Selecting Values


**Selecting columns **

Note - This is also called a pandas series

In [25]:
df['A']

0    0.442706
1    0.914644
2    0.626000
3    0.351729
4    0.938564
5    0.443930
6    0.827018
7    0.463182
8    0.081394
9    0.930465
Name: A, dtype: float64

In [8]:
type(df['A'])

pandas.core.series.Series

In [28]:
df[['A','B']]

A         B
0  0.442706  0.490083
1  0.914644  0.708358
2  0.626000  0.085339
3  0.351729  0.105410
4  0.938564  0.117120
5  0.443930  0.576886
6  0.827018  0.274479
7  0.463182  0.992580
8  0.081394  0.294326
9  0.930465  0.620387

**Selecting range of rows **


In [29]:
df[0:4]

A         B         C         D
0  0.442706  0.490083  0.603536  0.438479
1  0.914644  0.708358  0.561124  0.091168
2  0.626000  0.085339  0.687242  0.601120
3  0.351729  0.105410  0.923684  0.933026

**Selecting a particular row **


In [46]:
df

Employees  amount  count
0         a       1      2
1         a       1      2
2         a       2      2
3         b       1      2
4         b       1      2
5         c       1      2

In [30]:
df.loc[0]

A    0.442706
B    0.490083
C    0.603536
D    0.438479
Name: 0, dtype: float64

**Selecting a row and column **

In [10]:
df.loc[0,['A','B']]

A    0.148710
B    0.255946
Name: 0, dtype: float64

In [48]:
#print(df)
#df.loc[:,['A']]

print(df.at[0,'A'])

5.0


In [49]:
df

A         B         C         D
0  5.0  5.000000  0.603536  0.438479
1  5.0  0.708358  0.561124  0.091168
2  5.0  0.085339  0.687242  0.601120
3  5.0  0.105410  0.923684  0.933026
4  5.0  0.117120  0.510514  0.440755
5  5.0  0.576886  0.658548  0.638392
6  5.0  0.274479  0.807155  0.875864
7  5.0  0.992580  0.715163  0.083248
8  5.0  0.294326  0.135184  0.997124
9  5.0  0.620387  0.985961  0.439743

**Using at instead for faster access , can't be used for a range **

In [60]:
for i in df.index:
    for j in df.columns:
        if (df.at[i,j] == 5):
            print(i,j)
            break

0 amount


In [17]:
df

A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
1  0.884613  0.366173  0.403009  0.059076
2  0.190153  0.379428  0.606521  0.670061
3  0.813650  0.865682  0.005590  0.833786
4  0.797834  0.530511  0.894112  0.368181
5  0.180576  0.837625  0.085812  0.325849
6  0.099598  0.170077  0.896005  0.045636
7  0.143263  0.313568  0.902985  0.922671
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656

In [20]:
df>=0.2

A      B      C      D
0  False   True   True   True
1   True   True   True  False
2  False   True   True   True
3   True   True  False   True
4   True   True   True   True
5  False   True  False   True
6  False  False   True  False
7  False   True   True   True
8   True   True   True   True
9   True   True   True  False

In [21]:
print(df[df > 0.2])


          A         B         C         D
0       NaN  0.255946  0.507216  0.679305
1  0.884613  0.366173  0.403009       NaN
2       NaN  0.379428  0.606521  0.670061
3  0.813650  0.865682       NaN  0.833786
4  0.797834  0.530511  0.894112  0.368181
5       NaN  0.837625       NaN  0.325849
6       NaN       NaN  0.896005       NaN
7       NaN  0.313568  0.902985  0.922671
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622       NaN


In [23]:
df.at[0,'A']

0.9611065240021954

**Selecting by position **

In [55]:
df.iloc[0]

A    5.000000
B    5.000000
C    0.603536
D    0.438479
Name: 0, dtype: float64

**Selecting by condition  **


In [61]:
print(df)
print(df[(df.amount>1) & (df.Employees == 'a')])


  Employees  amount  count
0         a       1      2
1         a       1      2
2         a       2      2
3         b       1      2
4         b       1      2
5         c       1      2
  Employees  amount  count
2         a       2      2


In [62]:
df[df.amount>4]

Empty DataFrame
Columns: [Employees, amount, count]
Index: []

## Missing Data

In [24]:
print(df)
print(df<.5)

          A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
1  0.884613  0.366173  0.403009  0.059076
2  0.190153  0.379428  0.606521  0.670061
3  0.813650  0.865682  0.005590  0.833786
4  0.797834  0.530511  0.894112  0.368181
5  0.180576  0.837625  0.085812  0.325849
6  0.099598  0.170077  0.896005  0.045636
7  0.143263  0.313568  0.902985  0.922671
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656
       A      B      C      D
0   True   True  False  False
1  False   True   True   True
2   True   True  False  False
3  False  False   True  False
4  False  False  False   True
5   True  False   True   True
6   True   True  False   True
7   True   True  False  False
8  False   True  False   True
9  False   True  False   True


In [25]:
df2=df[df<.8]
print(df2)

          A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
1       NaN  0.366173  0.403009  0.059076
2  0.190153  0.379428  0.606521  0.670061
3       NaN       NaN  0.005590       NaN
4  0.797834  0.530511       NaN  0.368181
5  0.180576       NaN  0.085812  0.325849
6  0.099598  0.170077       NaN  0.045636
7  0.143263  0.313568       NaN       NaN
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656


**Drop all rows which have NaN **


In [26]:
df2.dropna()

A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
2  0.190153  0.379428  0.606521  0.670061
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656

**Replace NaN with other values **


In [27]:
df2.fillna(value=1)

A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
1  1.000000  0.366173  0.403009  0.059076
2  0.190153  0.379428  0.606521  0.670061
3  1.000000  1.000000  0.005590  1.000000
4  0.797834  0.530511  1.000000  0.368181
5  0.180576  1.000000  0.085812  0.325849
6  0.099598  0.170077  1.000000  0.045636
7  0.143263  0.313568  1.000000  1.000000
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656

## Statistical Operations

**Taking mean **

In [28]:
df

A         B         C         D
0  0.148710  0.255946  0.507216  0.679305
1  0.884613  0.366173  0.403009  0.059076
2  0.190153  0.379428  0.606521  0.670061
3  0.813650  0.865682  0.005590  0.833786
4  0.797834  0.530511  0.894112  0.368181
5  0.180576  0.837625  0.085812  0.325849
6  0.099598  0.170077  0.896005  0.045636
7  0.143263  0.313568  0.902985  0.922671
8  0.665560  0.226335  0.702292  0.288820
9  0.560362  0.277237  0.506622  0.193656

In [29]:
df.mean()

A    0.448432
B    0.422258
C    0.551017
D    0.438704
dtype: float64

**Mean in other axis **

In [73]:
df.mean(axis = 1)

0    0.308227
1    0.575665
2    0.325544
3    0.522733
4    0.377592
5    0.721912
6    0.726775
7    0.254704
8    0.448321
9    0.479884
dtype: float64

**groupby function **

In [30]:
#Creating a dataframe
d = {'amount':[1,1,2,1,1,1],
     'count':[2,2,2,2,2,2],
     'Employees':['a','a','a','b','b','c']}

df = pd.DataFrame(d)
df

Employees  amount  count
0         a       1      2
1         a       1      2
2         a       2      2
3         b       1      2
4         b       1      2
5         c       1      2

In [6]:
# Create group object
one = df.groupby('Employees')
print(one)
# Apply sum function
print(one.sum())

           amount  count
Employees               
a               4      6
b               2      4
c               1      2


In [7]:
# Create group object
one = df.groupby('Employees')

# Apply sum function
grouped_by_df = one.sum()

grouped_by_df.index

Index(['a', 'b', 'c'], dtype='object', name='Employees')

In [8]:
one.sum().index

Index(['a', 'b', 'c'], dtype='object', name='Employees')

In [9]:
print(df)
letterone = df.groupby(['Employees','amount']).sum()
print(letterone)

  Employees  amount  count
0         a       1      2
1         a       1      2
2         a       2      2
3         b       1      2
4         b       1      2
5         c       1      2
                  count
Employees amount       
a         1           4
          2           2
b         1           4
c         1           2


**To get more info about how data is grouped by **

In [10]:
letterone.index

MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
           labels=[[0, 0, 1, 2], [0, 1, 0, 0]],
           names=['Employees', 'amount'])

**You may want to not have the columns you are grouping by become your index, this can be easily achieved as shown below. **

In [31]:
letterone = df.groupby(['Employees','amount'], as_index=False).sum()
letterone

Employees  amount  count
0         a       1      4
1         a       2      2
2         b       1      4
3         c       1      2

In [32]:
letterone.index

Int64Index([0, 1, 2, 3], dtype='int64')