# Pandas Basics

**Importing the packages **

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

**Creating a dataframe **

In [2]:
print(np.random.rand(10,4))

[[0.79946883 0.11953766 0.23309342 0.05775292]
 [0.32853621 0.89153362 0.54136587 0.39361114]
 [0.3668966  0.95395554 0.3210871  0.38506047]
 [0.91572242 0.61800824 0.9774076  0.23476568]
 [0.10362312 0.33901087 0.01445833 0.0408893 ]
 [0.18491935 0.24263761 0.38665806 0.43165905]
 [0.61647054 0.15130089 0.87484198 0.0139372 ]
 [0.65898605 0.53603861 0.53750314 0.17637579]
 [0.82192209 0.48918859 0.24668161 0.58554658]
 [0.46738843 0.19201512 0.84399108 0.70735359]]


In [29]:
df=pd.DataFrame(np.random.rand(10,4), columns=['A','B','C','D'])
print(df)

          A         B         C         D
0  0.178717  0.871758  0.143516  0.954249
1  0.839102  0.688607  0.521632  0.212632
2  0.902968  0.482876  0.067732  0.933259
3  0.290010  0.318353  0.224602  0.839075
4  0.701344  0.761897  0.045366  0.729000
5  0.983213  0.217733  0.951447  0.502358
6  0.834799  0.462368  0.233298  0.598572
7  0.392423  0.134407  0.919557  0.697934
8  0.224526  0.912945  0.943199  0.338348
9  0.092820  0.708566  0.538164  0.428649


In [30]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

**Creating a dataframe with dictionary **

In [8]:
dict1 = {'A' : [10,20],'B' : [20,100],'C' : [30,40],'D' : [40,50]}
df2 = pd.DataFrame(dict1)
print(df2)

    A    B   C   D
0  10   20  30  40
1  20  100  40  50


**Looking at the variable types **

In [9]:
df2.dtypes

A    int64
B    int64
C    int64
D    int64
dtype: object

**looking at the top few values, default 5 **

In [13]:
df.head()

A         B         C         D
0  0.189296  0.045330  0.508695  0.982386
1  0.114832  0.722614  0.595128  0.482587
2  0.694801  0.385834  0.051299  0.375857
3  0.365497  0.474093  0.994173  0.660481
4  0.975872  0.100138  0.139201  0.655264

**Looking at the last few values **

In [14]:
df.tail()

A         B         C         D
5  0.404993  0.416653  0.029580  0.224600
6  0.729537  0.402017  0.088864  0.082624
7  0.603319  0.727190  0.357671  0.296230
8  0.002800  0.629528  0.303383  0.453839
9  0.838305  0.752742  0.739659  0.565350

**To get the indexes **


In [15]:
print(df)
df.index

          A         B         C         D
0  0.189296  0.045330  0.508695  0.982386
1  0.114832  0.722614  0.595128  0.482587
2  0.694801  0.385834  0.051299  0.375857
3  0.365497  0.474093  0.994173  0.660481
4  0.975872  0.100138  0.139201  0.655264
5  0.404993  0.416653  0.029580  0.224600
6  0.729537  0.402017  0.088864  0.082624
7  0.603319  0.727190  0.357671  0.296230
8  0.002800  0.629528  0.303383  0.453839
9  0.838305  0.752742  0.739659  0.565350


RangeIndex(start=0, stop=10, step=1)

**To get the column names **

In [31]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [32]:
hasattr(df, 'A')

True

**To get the values **

In [33]:
df.values

array([[0.17871682, 0.87175817, 0.14351608, 0.95424895],
       [0.83910215, 0.68860725, 0.52163233, 0.2126315 ],
       [0.90296836, 0.48287579, 0.06773215, 0.93325916],
       [0.29001029, 0.31835333, 0.22460217, 0.83907533],
       [0.70134408, 0.76189714, 0.04536613, 0.72900046],
       [0.98321324, 0.2177326 , 0.95144738, 0.50235824],
       [0.83479887, 0.4623679 , 0.23329845, 0.59857241],
       [0.39242305, 0.13440699, 0.91955671, 0.69793414],
       [0.22452615, 0.91294468, 0.94319872, 0.33834779],
       [0.09281954, 0.70856622, 0.53816365, 0.42864882]])

**To get quick statistics about the data **

In [34]:
df.describe()

A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.543992   0.555951   0.458851   0.623408
std     0.340705   0.273480   0.369512   0.252075
min     0.092820   0.134407   0.045366   0.212632
25%     0.240897   0.354357   0.163788   0.447076
50%     0.546884   0.585742   0.377465   0.648253
75%     0.838026   0.748564   0.824208   0.811557
max     0.983213   0.912945   0.951447   0.954249

**For sorting the index **

In [37]:
df.sort_index(axis=0, ascending=True)

A         B         C         D
0  0.178717  0.871758  0.143516  0.954249
1  0.839102  0.688607  0.521632  0.212632
2  0.902968  0.482876  0.067732  0.933259
3  0.290010  0.318353  0.224602  0.839075
4  0.701344  0.761897  0.045366  0.729000
5  0.983213  0.217733  0.951447  0.502358
6  0.834799  0.462368  0.233298  0.598572
7  0.392423  0.134407  0.919557  0.697934
8  0.224526  0.912945  0.943199  0.338348
9  0.092820  0.708566  0.538164  0.428649

**For sorting by a column **

In [38]:
df.sort_values(by='A', ascending = False)

A         B         C         D
5  0.983213  0.217733  0.951447  0.502358
2  0.902968  0.482876  0.067732  0.933259
1  0.839102  0.688607  0.521632  0.212632
6  0.834799  0.462368  0.233298  0.598572
4  0.701344  0.761897  0.045366  0.729000
7  0.392423  0.134407  0.919557  0.697934
3  0.290010  0.318353  0.224602  0.839075
8  0.224526  0.912945  0.943199  0.338348
0  0.178717  0.871758  0.143516  0.954249
9  0.092820  0.708566  0.538164  0.428649

## Selecting Values


**Selecting columns **

Note - This is also called a pandas series

In [41]:
df['A']

0    0.178717
1    0.839102
2    0.902968
3    0.290010
4    0.701344
5    0.983213
6    0.834799
7    0.392423
8    0.224526
9    0.092820
Name: A, dtype: float64

In [42]:
df[['A','B']]

A         B
0  0.178717  0.871758
1  0.839102  0.688607
2  0.902968  0.482876
3  0.290010  0.318353
4  0.701344  0.761897
5  0.983213  0.217733
6  0.834799  0.462368
7  0.392423  0.134407
8  0.224526  0.912945
9  0.092820  0.708566

**Selecting range of rows **


In [48]:
df[0:1]

A         B         C         D
0  0.178717  0.871758  0.143516  0.954249

**Selecting a particular row **


In [49]:
df.loc[0]

A    0.178717
B    0.871758
C    0.143516
D    0.954249
Name: 0, dtype: float64

**Selecting a row and column **

In [51]:
df.loc[0,['A']]

A    0.178717
Name: 0, dtype: float64

In [55]:
df.loc[:,['A']]

A
0  0.178717
1  0.839102
2  0.902968
3  0.290010
4  0.701344
5  0.983213
6  0.834799
7  0.392423
8  0.224526
9  0.092820

**Using at instead for faster access , can't be used for a range **

In [56]:
df.at[0,'A']

0.17871682323666305

**Selecting by position **

In [21]:
df.iloc[0]

A    0.999031
B    0.193062
C    0.758188
D    0.966068
Name: 0, dtype: float64

**Selecting by condition  **


In [22]:
df.A>0.4

0     True
1    False
2    False
3     True
4    False
5     True
6    False
7     True
8    False
9     True
Name: A, dtype: bool

In [23]:
df[df.A>0.4]

A         B         C         D
0  0.999031  0.193062  0.758188  0.966068
3  0.893523  0.237982  0.912260  0.264787
5  0.857072  0.695623  0.400567  0.639996
7  0.801155  0.723512  0.909308  0.447669
9  0.560863  0.747727  0.205355  0.700041

## Missing Data

In [57]:
empty_df = pd.DataFrame()
print(empty_df)

Empty DataFrame
Columns: []
Index: []


In [61]:
print(df)
print(df<.5)

          A         B         C         D
0  0.178717  0.871758  0.143516  0.954249
1  0.839102  0.688607  0.521632  0.212632
2  0.902968  0.482876  0.067732  0.933259
3  0.290010  0.318353  0.224602  0.839075
4  0.701344  0.761897  0.045366  0.729000
5  0.983213  0.217733  0.951447  0.502358
6  0.834799  0.462368  0.233298  0.598572
7  0.392423  0.134407  0.919557  0.697934
8  0.224526  0.912945  0.943199  0.338348
9  0.092820  0.708566  0.538164  0.428649
       A      B      C      D
0   True  False   True  False
1  False  False  False   True
2  False   True   True  False
3   True   True   True  False
4  False  False   True  False
5  False   True  False  False
6  False   True   True  False
7   True   True  False  False
8   True  False  False   True
9   True  False  False   True


In [62]:
df2=df[df<.5]
print(df2)

          A         B         C         D
0  0.178717       NaN  0.143516       NaN
1       NaN       NaN       NaN  0.212632
2       NaN  0.482876  0.067732       NaN
3  0.290010  0.318353  0.224602       NaN
4       NaN       NaN  0.045366       NaN
5       NaN  0.217733       NaN       NaN
6       NaN  0.462368  0.233298       NaN
7  0.392423  0.134407       NaN       NaN
8  0.224526       NaN       NaN  0.338348
9  0.092820       NaN       NaN  0.428649


In [26]:
df<.5

A      B      C      D
0  False   True  False  False
1   True   True  False   True
2   True  False  False   True
3  False   True  False   True
4   True  False   True   True
5  False  False   True  False
6   True   True   True  False
7  False  False  False   True
8   True  False   True   True
9  False  False   True  False

**Drop all rows which have NaN **


In [27]:
df2.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

**Replace NaN with other values **


In [63]:
df2.fillna(value=1)

A         B         C         D
0  0.178717  1.000000  0.143516  1.000000
1  1.000000  1.000000  1.000000  0.212632
2  1.000000  0.482876  0.067732  1.000000
3  0.290010  0.318353  0.224602  1.000000
4  1.000000  1.000000  0.045366  1.000000
5  1.000000  0.217733  1.000000  1.000000
6  1.000000  0.462368  0.233298  1.000000
7  0.392423  0.134407  1.000000  1.000000
8  0.224526  1.000000  1.000000  0.338348
9  0.092820  1.000000  1.000000  0.428649

## Statistical Operations

**Taking mean **

In [64]:
df

A         B         C         D
0  0.178717  0.871758  0.143516  0.954249
1  0.839102  0.688607  0.521632  0.212632
2  0.902968  0.482876  0.067732  0.933259
3  0.290010  0.318353  0.224602  0.839075
4  0.701344  0.761897  0.045366  0.729000
5  0.983213  0.217733  0.951447  0.502358
6  0.834799  0.462368  0.233298  0.598572
7  0.392423  0.134407  0.919557  0.697934
8  0.224526  0.912945  0.943199  0.338348
9  0.092820  0.708566  0.538164  0.428649

In [65]:
df.mean()

A    0.543992
B    0.555951
C    0.458851
D    0.623408
dtype: float64

**Mean in other axis **

In [66]:
df.mean(axis = 1)

0    0.537060
1    0.565493
2    0.596709
3    0.418010
4    0.559402
5    0.663688
6    0.532259
7    0.536080
8    0.604754
9    0.442050
dtype: float64

**groupby function **

In [69]:
#Creating a dataframe
d = {'amount':[1,1,2,1,1,1],
     'count':[2,2,2,2,2,2],
     'Employees':['a','a','a','b','b','c']}

df = pd.DataFrame(d)
df

Employees  amount  count
0         a       1      2
1         a       1      2
2         a       2      2
3         b       1      2
4         b       1      2
5         c       1      2

In [73]:
# Create group object
one = df.groupby('Employees')

# Apply sum function
one.sum()

amount  count
Employees               
a               4      6
b               2      4
c               1      2

In [75]:
# Create group object
one = df.groupby('Employees')

# Apply sum function
grouped_by_df = one.sum()

grouped_by_df.index

Index(['a', 'b', 'c'], dtype='object', name='Employees')

In [34]:
one.sum().index

Index(['a', 'b', 'c'], dtype='object', name='letter')

In [78]:
print(df)
letterone = df.groupby(['Employees','amount']).sum()
print(letterone)

  Employees  amount  count
0         a       1      2
1         a       1      2
2         a       2      2
3         b       1      2
4         b       1      2
5         c       1      2
                  count
Employees amount       
a         1           4
          2           2
b         1           4
c         1           2


**To get more info about how data is grouped by **

In [79]:
letterone.index

MultiIndex(levels=[['a', 'b', 'c'], [1, 2]],
           labels=[[0, 0, 1, 2], [0, 1, 0, 0]],
           names=['Employees', 'amount'])

**You may want to not have the columns you are grouping by become your index, this can be easily achieved as shown below. **

In [82]:
letterone = df.groupby(['Employees','amount'], as_index=False).sum()
letterone

Employees  amount  count
0         a       1      4
1         a       2      2
2         b       1      4
3         c       1      2

In [83]:
letterone.index

Int64Index([0, 1, 2, 3], dtype='int64')